export default {
  /* MAIN COLORS */
  COLOR_YELLOW: '#FF9F1C',
  COLOR_RED: '#FF4040',
  COLOR_GREEN: '#2EC4B6',

  /* GREY COLORS */
  COLOR_DARK: '#0A1014',
  COLOR_GREY: '#1B2329',
  COLOR_MIDGREY: '#353F4C',
  COLOR_LIGHTGREY: '#7A8C99',
  COLOR_WHITE: '#FFFFFF',

  /* NAMED COLORS */
  COLOR_DEFAULT: '#FFFFFF',
  COLOR_SECONDARY: '#7A8C99',
  COLOR_ACTIVE: '#2EC4B6',
  COLOR_NEGATIVE: '#FF4040',
  COLOR_HIGHLIGHT: '#FF9F1C',
  COLOR_DISABLED: '#1B2329',

  /* TYPOGRAPHY */
  FONT_SIZE_GIANT: '80pt',
  FONT_SIZE_BIGGER: '24pt',
  FONT_SIZE_BIG: '20pt',
  FONT_SIZE_REGULAR: '16pt',
  FONT_WEIGHT_BOLD: '700',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_REGULAR: '400',
  BORDER_RADIUS: '4px',
};
