/**
  Action Types
 */
const SEARCH_TERM_CHANGED = "SEARCH_TERM_CHANGED"
const MOVIES = "MOVIES"
const SINGLE_MOVIE = "SINGLE_MOVIE"
const FAVORITES = "FAVORITES"
const TOGGLE_FAVORITE = "TOGGLE_FAVORITE"
const ADD_FAVORITE = "ADD_FAVORITE"

export default {
    SEARCH_TERM_CHANGED,
    MOVIES,
    SINGLE_MOVIE,
    FAVORITES,
    TOGGLE_FAVORITE,
    ADD_FAVORITE
}