export Logo from './Logo'
export Heart from './Heart'
export Arrow from './Arrow'
export IMDB from './IMDB'
export RottenTomatoes from './RottenTomatoes'
export Movie from './Movie'
export Dead from './Dead'
export FightClub from './FightClub'
